In [1]:
import numpy as np

In [2]:
num = np.array([1,2,3,4,5,6])

In [3]:
print(num)

[1 2 3 4 5 6]


In [4]:
x = [56,67,78,89,90,34]
x*2

[56, 67, 78, 89, 90, 34, 56, 67, 78, 89, 90, 34]

In [5]:
num * 2

array([ 2,  4,  6,  8, 10, 12])

In [6]:
num / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

In [7]:
num - 10

array([-9, -8, -7, -6, -5, -4])

In [10]:
num > 1

array([False,  True,  True,  True,  True,  True])

In [11]:
5 in num

True

In [12]:
10 not in num

True

In [13]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
list(range(10,0,-2))

[10, 8, 6, 4, 2]

In [16]:
list(random())

<class 'NameError'>: name 'random' is not defined

In [17]:
from random import random

In [21]:
print(random())

0.7926010347287278


In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,10,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25,
       5.5 , 5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  ,
       8.25, 8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75])

In [25]:
np.arange(0,10,random())

array([0.        , 0.04142984, 0.08285968, 0.12428952, 0.16571935,
       0.20714919, 0.24857903, 0.29000887, 0.33143871, 0.37286855,
       0.41429839, 0.45572822, 0.49715806, 0.5385879 , 0.58001774,
       0.62144758, 0.66287742, 0.70430726, 0.74573709, 0.78716693,
       0.82859677, 0.87002661, 0.91145645, 0.95288629, 0.99431612,
       1.03574596, 1.0771758 , 1.11860564, 1.16003548, 1.20146532,
       1.24289516, 1.28432499, 1.32575483, 1.36718467, 1.40861451,
       1.45004435, 1.49147419, 1.53290403, 1.57433386, 1.6157637 ,
       1.65719354, 1.69862338, 1.74005322, 1.78148306, 1.8229129 ,
       1.86434273, 1.90577257, 1.94720241, 1.98863225, 2.03006209,
       2.07149193, 2.11292177, 2.1543516 , 2.19578144, 2.23721128,
       2.27864112, 2.32007096, 2.3615008 , 2.40293063, 2.44436047,
       2.48579031, 2.52722015, 2.56864999, 2.61007983, 2.65150967,
       2.6929395 , 2.73436934, 2.77579918, 2.81722902, 2.85865886,
       2.9000887 , 2.94151854, 2.98294837, 3.02437821, 3.06580

In [27]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
int(np.ones(10))

<class 'TypeError'>: only size-1 arrays can be converted to Python scalars

In [31]:
np.empty(9)

array([1.54435120e-307, 2.12199579e-314, 2.12199580e-314, 2.24881591e-294,
       1.06099790e-312, 7.49753738e-308, 2.12199579e-314, 2.12199580e-314,
       2.24872034e-294])

In [33]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [34]:
x = np.array([[4,5,6],[7,8,9]])

In [35]:
x

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
x.shape

(2, 3)

In [37]:
x.size

6

In [38]:
x.ndim

2

In [39]:
x[1][2]

9

In [40]:
x.reshape(6,1)

array([[4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [41]:
x.reshape(-1,6)

array([[4, 5, 6, 7, 8, 9]])

In [42]:
x.flatten()

array([4, 5, 6, 7, 8, 9])

In [45]:
### Functions

In [49]:
import pandas as pd

In [50]:
s = pd.Series([56,67,78,89])

In [51]:
s

0    56
1    67
2    78
3    89
dtype: int64

In [57]:
s = pd.Series([56,67,78,89,99,90,18], index = range(100,107))

In [58]:
s

100    56
101    67
102    78
103    89
104    99
105    90
106    18
dtype: int64

In [59]:
s[103]

89

In [60]:
s.size

7

In [62]:
s.dtype

dtype('int64')

In [74]:
import pandas as pd

df = pd.DataFrame({'Name': ['Sahil', 'manasi', 'vasudha','shubham'], 'Age': [23, 22, 22, 24], 'Roll_no': [220188, 2201058, 2201047, 220189]})


In [75]:
df

Name  Age  Roll_no
0    Sahil   23   220188
1   manasi   22  2201058
2  vasudha   22  2201047
3  shubham   24   220189

In [78]:
df.size

12

In [79]:
df.shape

(4, 3)

In [80]:
df.columns

Index(['Name', 'Age', 'Roll_no'], dtype='object')

In [81]:
df.T

0        1        2        3
Name      Sahil   manasi  vasudha  shubham
Age          23       22       22       24
Roll_no  220188  2201058  2201047   220189

In [82]:
list(s)

[56, 67, 78, 89, 99, 90, 18]

In [83]:
s.values

array([56, 67, 78, 89, 99, 90, 18], dtype=int64)

In [84]:
tuple(s)

(56, 67, 78, 89, 99, 90, 18)

In [86]:
df.values

array([['Sahil', 23, 220188],
       ['manasi', 22, 2201058],
       ['vasudha', 22, 2201047],
       ['shubham', 24, 220189]], dtype=object)

In [88]:
dict(s)

{100: 56, 101: 67, 102: 78, 103: 89, 104: 99, 105: 90, 106: 18}

In [89]:
df.head()

Name  Age  Roll_no
0    Sahil   23   220188
1   manasi   22  2201058
2  vasudha   22  2201047
3  shubham   24   220189

In [90]:
df['Age'].describe

<bound method NDFrame.describe of 0    23
1    22
2    22
3    24
Name: Age, dtype: int64>

In [102]:
x = np.random.randint(0, 100, size=(10))
print(x)

[41 88 86 32 69 50  5 30  4 56]


In [105]:
x.mean()

46.1

In [106]:
x = np.random.randint(0,200,15)

In [107]:
x

array([144,  68,  40, 142,  49, 134,   8,  65, 116, 147,  91,  86,  92,
       180,   9])

In [113]:
import os
os.getcwd()

'/drive'

In [114]:
os.getcwd()

'/drive'